DROP TABLE IF EXISTS NTTEXTComm_EntryVUs;
DROP TABLE IF EXISTS NTTEXTComm_Rdgs;
DROP TABLE IF EXISTS NTTEXTComm_VUReference;
DROP TABLE IF EXISTS NTTEXTComm_VUs;
DROP TABLE IF EXISTS NTTEXTComm_Entries;